app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Routes File
  |--------------------------------------------------------------------------
  |
  | Here is where you will register all of the routes in an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::group(['namespace' => 'Store', 'middleware' => ['web', 'locale', 'store']], function() {

	Route::get('/', 'FrontController@home');


	/* Products */

	Route::get('subhome/{id}', 'ProductsController@subhome');


	/* Rutas reales slug */

	Route::get('detail/{id}', 'ProductsController@detail');
	Route::get('color/{id}', 'ProductsController@color');
	Route::get('prods/{id}', 'ProductsController@prods');
	Route::get('moreProds/{id}', 'ProductsController@moreProds');
	Route::get('searchMore/{q}', 'ProductsController@searchMore');

	Route::get('loadCategoryInfo/{id}/{pid?}/{pidc?}', 'ProductsController@loadCategoryInfo');


	Route::get('imageByColor/{id}', 'ProductsController@imageByColor');
	//Route::controller('products', 'ProductsController');
	//Route::controller('stores', 'StoresController');

	/* Users */
	Route::controller('users', 'UsersController');
	Route::post('recoverypassword', 'UsersController@recoveryPassword');
	Route::get('/passwordReset/{id}/{recovery}', 'UsersController@viewPasswordReset');
	Route::post('/passwordReset', 'UsersController@passwordReset');
	Route::post('/newsletter', 'UsersController@postNewsletters');

	/* Blog */
	Route::post('blog/comments/save', 'BlogController@postComment');
	Route::get('blog/{category}/{slug}/{id}', 'BlogController@getArticle');
	Route::controller('blog', 'BlogController');
	
	Route::get('loadMore/{page}', 'FrontController@loadMore');
	Route::get('loadMore/{page}/{category}', 'FrontController@loadMore');
/*pages  store */
//--Route::get('/{url}', 'PageController@getPage'); //---RB ***************************
});

/*
 * AUTH
 */

Route::group(['namespace' => 'Auth', 'middleware' => ['web']], function () {

	Route::get('/login', ['uses' => 'AuthController@getLogin', 'as' => 'auth/login']);

	Route::post('/login', 'AuthController@postLogin');

	Route::get('/register', ['uses' => 'AuthController@getRegister', 'as' => 'auth/register']);

	Route::post('/register', 'AuthController@postRegister');

	Route::get('/logout', ['uses' => 'AuthController@getLogout', 'as' => 'auth/logout']);

	Route::get('/forgot', ['uses' => 'AuthController@getForgot', 'as' => 'auth/forgot']);

	Route::post('/forgot', ['uses' => 'PasswordController@postEmail']);

	Route::get('/password/reset/{token}', ['uses' => 'PasswordController@getReset', 'as' => 'auth/reset']);

	Route::post('/password/reset/{token}', ['uses' => 'PasswordController@postReset']);

	Route::get('/activate/account/{token}', ['uses' => 'AuthController@getActivate', 'as' => 'auth/activate']);

	Route::post('/activate/account/{token}', ['uses' => 'AuthController@postActivate']);

	Route::get('/check/email', ['uses' => 'AuthController@getCheckEmail']);
});

//Route::auth();

/*
 *
 */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['web', 'auth', 'store', 'acl']], function() {

	Route::get('/', function() {
		return redirect(route('admin/dashboard'));
	});

	Route::get('/action/country/{id}', ['uses' => 'AdminController@setCountry']);
	Route::get('/action/lang/{id}', ['uses' => 'AdminController@setLang']);

	Route::get('/dashboard', ['uses' => 'HomeController@dashboard', 'as' => 'admin/dashboard']);

	Route::group(['namespace' => 'Catalog', 'prefix' => 'catalog'], function() {

		/* Categories */
		Route::controller('categories', 'CategoriesController');

		/* Products */

		/*
		  Route::get('products/edit/{id}', 'ProductsController@edit');
		  Route::get('products/show/{id}', 'ProductsController@show');
		  Route::post('products/update/{id}', 'ProductsController@update');
		  Route::get('products/destroy/{id}', 'ProductsController@destroy');
		  Route::post('products/store', 'ProductsController@store');
		  Route::get('products/upload', 'ProductsController@getUpload');
		  Route::get('products/uploadlog', 'ProductsController@getUploadLog');
		  Route::get('products/tags', 'ProductsController@getTags');
		  Route::get('products/productbytags/{tag}', 'ProductsController@productbytags');
		  Route::get('products/borrartags/{tag}', 'ProductsController@borrartags');
		  Route::resource('products', 'ProductsController');
		 */

		Route::get('/check/code/{id?}', ['uses' => 'ProductsController@checkCode']);
		Route::get('products/uploadlog', 'ProductsController@getUploadLog');
		Route::controller('products', 'ProductsController');

		/* Products Images */
		Route::get('productsImages/destroy/{id}', 'ProductsImagesController@destroy');
		Route::controller('productsImages', 'ProductsImagesController');

		/* References */
		Route::get('references', 'ReferencesController@index');
		Route::get('references/edit/{id}', 'ReferencesController@edit');
		Route::get('references/create', 'ReferencesController@create');
		Route::get('references/show/{id}', 'ReferencesController@show');
		Route::post('references/update/{id}', 'ReferencesController@update');
		Route::get('references/destroy/{id}', 'ReferencesController@destroy');
		Route::post('references/store', 'ReferencesController@store');
		Route::get('references/deleteDataSheet/{id}', 'ReferencesController@deleteDataSheet');
		Route::get('references/deleteuManual/{id}', 'ReferencesController@deleteuManual');
		Route::get('references/deletemManual/{id}', 'ReferencesController@deletemManual');
		Route::get('references/deleteGuarantee/{id}', 'ReferencesController@deleteGuarantee');
		Route::get('references/category', 'ReferencesController@category');

		/* Stores */
		Route::controller('stores', 'StoresController');
	});

	Route::group(['namespace' => 'Appearance', 'prefix' => 'appearance'], function() {
		/* Menu */
		Route::get('menu/categories/{id}', 'MenuController@categories');
		//Route::resource('menu', 'MenuController');
		Route::controller('menu', 'MenuController');

		Route::controller('slider', 'SliderController');
		Route::controller('footer', 'FooterController');

		/* Carrusel */
		Route::resource('carrusel', 'CarruselController');
		Route::get('carrusel/edit/{id}', 'CarruselController@edit');
		Route::post('carrusel/update/{id}', 'CarruselController@update');
		Route::get('carrusel/destroy/{id}', 'CarruselController@destroy');
		Route::get('carrusel/change-status/{id}/{status}', 'CarruselController@changeStatus');
		Route::post('carrusel/store', 'CarruselController@store');

		/* Banners home */
		Route::controller('banners_home', 'BannersHomeController');

		/* Banners site */
		Route::controller('banners_site', 'BannersSiteController');
	});

	/* USERS */
	Route::get('profile', 'UsersController@getProfile');
	Route::get('profile/edit', 'UsersController@getEditProfile');
	Route::post('profile/edit', 'UsersController@postEditProfile');
	Route::get('profile/change_password', 'UsersController@getChangePassword');
	Route::post('profile/change_password', 'UsersController@postChangePassword');
	//Route::post('/users/create', 'UsersController@postCreate');
	Route::controller('users', 'UsersController');

	/* CUSTOMERS */
	Route::get('customers', 'CustomersController@index');
	Route::get('customers/show/{id}', 'CustomersController@show');
	Route::get('customers/subscribers', 'CustomersController@subscribers');
	Route::get('customers/unsubscribe/{id}', 'CustomersController@unsubscribe');

	/* COUNTRIES */
	Route::controller('countries', 'CountriesController');

	/* DEPARTMENTS */
	Route::controller('departments', 'DepartmentsController');

	/* CITIES */
	Route::controller('cities', 'CitiesController');

	/* SERVICES */
	Route::controller('services', 'ServicesController');

	/* QUOTES */
	Route::get('quotes', 'QuotesController@index');
	Route::get('quotes/show/{id}', 'QuotesController@show');
	Route::get('quotes/edit/{id}', 'QuotesController@edit');
	Route::get('quotes/setManager', 'QuotesController@setManager');
	Route::get('quotes/setRoom', 'QuotesController@setRoom');
	Route::get('quotes/setStatus', 'QuotesController@setStatus');
	Route::get('quotes/setComment', 'QuotesController@setComment');
	Route::get('quotes/downloadQuotes', 'QuotesController@downloadQuotes');
	Route::controller('quotes', 'QuotesController');
	Route::get('/quotes', ['uses' => 'QuotesController@index', 'as' => 'admin/quotes']);

	/* SETTINGNS */
	Route::controller('settings', 'SettingsController');

	/* BLOGS */
	Route::controller('blog', 'BlogController');

/*pages---*/	
Route::controller('page', 'PageController'); //*

	/*SEO*/
	Route::controller('seo','SeoController');
});

/*
 * 	FRONT
 */
Route::group(['namespace' => 'Store', 'middleware' => ['web']], function() {
	Route::get('/customer/email', ['uses' => 'UsersController@getCheckEmail']);


});


Route::group(['namespace' => 'Store', 'middleware' => ['web', 'locale', 'store']], function() {

Route::get('/{url}', 'PageController@getPage'); //---RB ***************************

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Carbon\Carbon;

class Category extends Model
{

	const STATUS_PENDING = 'pending';
	const STATUS_ACTIVE = 'active';
	const STATUS_BLOCKED = 'disabled';
	const MAX_LEVEL = 4;
	const DEFAULT_PICTURE = '/images/placeholder.png';
	const DEFAULT_PICTURE_CATEGORY_DESKTOP = '/images/placeholderCategoryDesktop.png';
	const DEFAULT_PICTURE_CATEGORY_MOBILE = '/images/placeholderCategoryMobile.png';
	const DEFAULT_PICTURE_HEADER = '/images/placeholderHeader.png';
	const AMBIENTES_CATEGORY = 1;
	const CATEGORY_EXPERTS = "A00005";
	const CATEGORY_IDEAS = "A00006";
	const CATEGORY_COLECCIONES = "A00004";

	/**
	* The database table used by the model.
	*
	* @var string
	*/
	protected $table = 'categories';

	/**
	* The attributes that are mass assignable.
	*
	* @var array
	*/
	protected $fillable = ['name', 'description'];

	/**
	* The attributes excluded from the model's JSON form.
	*
	* @var array
	*/
	protected $hidden = ['created_at', 'updated_at'];
	protected $appends = ['detail_url'];

	// --------------------- STATIC --------------------- //

	/**

	* The booting method of the model.
	* @return void
	*/
	protected static function boot()
	{

		static::saving(function($model) {
			if( isset($model->name) ) {
				$model->slug = strtolower(str_slug($model->name, "-"));
			}
		});

		static::created(function($model) {
			// create code

			if( isset($model->id) ) {
				$model->code = "A" . str_pad($model->id, 5, "0", STR_PAD_LEFT);

				$model->save();
			}
		});

		static::deleted(function($model) {
			self::onDeleteCategory($model);
		});
	}


	public static function onDeleteCategory($model){
		//Elimina banners del menu asociados a la categoria eliminada
		BannerMenu::where(['entity_id' => $model->id, 'type' => BannerMenu::TYPE_PRODUCT])
		->update(['status' => BannerMenu::STATUS_DISABLED, 'entity_id' => null]);

		//Elimina banners del sitio asociados a la categoria eliminada
		BannerSite::where(['entity_id' => $model->id, 'type' => BannerSite::TYPE_PRODUCT])
		->update(['status' => BannerSite::STATUS_DISABLED, 'entity_id' => null]);

		//Elimina banners del home asociados a la categoria eliminada
		BannerHome::where(['entity_id' => $model->id, 'type' => BannerHome::TYPE_PRODUCT])
		->update(['status' => BannerHome::STATUS_DISABLED, 'entity_id' => null]);

		//Elimina banners de categorias asociados a la categoria eliminada
		BannerCategory::where(['entity_id' => $model->id, 'type' => BannerCategory::TYPE_PRODUCT])
		->update(['status' => BannerCategory::STATUS_DISABLED, 'entity_id' => null]);

		//Elimina carruseles asociados al producto a la categoria eliminada
		Carrusel::where(['entity_id' => $model->id, 'type' => Carrusel::TYPE_PRODUCT])
		->update(['status' => Carrusel::STATUS_DISABLED, 'entity_id' => null]);

	}

	public static function getTopLevelCategories()
	{
		return self::where([
			'status' => self::STATUS_ACTIVE,
			'parent' => null,
		]);
	}

	public static function buildCategoriesTree()
	{
		$tree = self::getTopLevelCategories()->get();
		foreach( $tree as &$leaf ) {
			self::getCategoriesTree($leaf);
		}
		return $tree;
	}

	public static function buildCategoriesTreeCache($storeId){

		config(['database.default' => $storeId]);

		if( Cache::has('categories_' . $storeId) ) {
			$tree = Cache::get('categories_' . $storeId, []);
		}
		else {
			$tree = self::buildCategoriesTree();
			if( count($tree) > 0 ) {
				$expiresAt = Carbon::now()->addMinutes(60);
				Cache::add('categories_' . $storeId, $tree, $expiresAt);
			}
		}
		return $tree;
	}

	public static function getCategoriesTree(&$category)
	{
		foreach( $category->categories as &$child ) {
			self::getCategoriesTree($child);
		}
		return $category;
	}

	public static function getCategoriesArray($category, &$array)
	{
		foreach( $category->categories as $child ) {
			self::getCategoriesArray($child, $array);
		}
		$array[] = $category;
	}

	public static function getLeafCategoriesArray($category, &$array)
	{
		if(count($category->categories))
			foreach( $category->categories as $child )
				self::getLeafCategoriesArray($child, $array);
		else{
			$flag = true;
			foreach ($array as $value) 
				if($value->slug == $category->slug) $flag = false;
			if($flag) $array[] = $category;
		}
	}

	public static function getCategoriesTreeParents(&$category)
	{
		if( $category->parentCategory != null ) {
			self::getCategoriesTreeParents($category->parentCategory);
		}
		return $category;
	}

	public static function getCategoriesArrayParents(&$category, &$array)
	{
		if( $category->parentCategory != null ) {
			self::getCategoriesArrayParents($category->parentCategory, $array);
		}
		$array[] = $category->slug;
	}

	public static function getBreadcrumbs($category, &$breadcrumbs)
	{
		if( $category->parentCategory != null ) {
			self::getBreadcrumbs($category->parentCategory, $breadcrumbs);
		}
		$breadcrumbs[] = $category;
		return $breadcrumbs;
	}

	public static function getChildCategories($childCategories, &$releatedCategories)
	{
		foreach( $childCategories as $childCategory ) {
			$releatedCategories['ids'][] = $childCategory->id;
			$releatedCategories['objects'][] = $childCategory;

			if( isset($childCategory->categories) ) {
				self::getChildCategories($childCategory->categories, $releatedCategories);
			}
		}
		return $releatedCategories;
	}

	// --------------------- METHODS --------------------- //

	public function categories()
	{
		return $this->hasMany('App\Models\Category', 'parent');
	}

	public function parentCategory()
	{
		return $this->belongsTo('App\Models\Category', 'parent');
	}

	//------------------------------------------------------------------------------------
	/* public function footerCategories(){
	return $this->belongsTo('App\Models\footerCategory', 'parent');
} */


public function getImageUrlAttribute($value){
	return $value ? $value : self::DEFAULT_PICTURE_CATEGORY_DESKTOP;
}

public function getImageMobileUrlAttribute($value){
	return $value ? $value : self::DEFAULT_PICTURE_CATEGORY_MOBILE;
}


public function getHeaderUrlAttribute($value){
	return $value ? $value : self::DEFAULT_PICTURE_HEADER;
}

public function isTwoColumns(){
	return (count($this->categories)==2);
}

public function isBig(){
	return (count($this->categories)>2);
}

public function isShort(){
	return (count($this->categories)==0);
}

public function isExpertsCategory(){
	return ($this->code==self::CATEGORY_EXPERTS);
}

public function isIdeasCategory(){
	return ($this->code==self::CATEGORY_IDEAS);
}

public function getDetailUrlAttribute(){
	return getUrlEntity($this);
}

public function parentOfCategory(){

	$id_parent = $this->parent;
	
	if(!$id_parent){
		return $this;
	}
	
	while(true){
		if($id_parent){
			$category = self::find($id_parent);
			$id_parent = $category->parent;
		}else{
			break;
		}
	}
	
	return $category;
}


}

app/Http/Controllers/Store/StoresController.php
<?php

namespace App\Http\Controllers\Store;

use Illuminate\Http\Request;
use App\Models\Department;
use App\Models\City;
use App\Models\Store;

class StoresController extends FrontController{


	public function getIndex(Request $request)
	{
		$storeId = config('store.id');
		$departments = Department::getDepartmentByCountry($storeId)->get();

		if(!$request->cookie('country')){
    		$value = config('store.id');
    	} else{
    		$value = $request->cookie('country');
    	}

    	$store = new Store();

		switch ($value){
			case "co":
				$store->latitude = 4.6482976;
				$store->longitude = -74.107807;
			break;
			case "us":
				$store->latitude = 	25.761681;
				$store->longitude = -80.191788;
			break;
			case "ec":
				$store->latitude = -0.180653;
				$store->longitude = -78.467834;
			break;
		}

		return view('store.pages.stores', [
			'departments' => $departments,
			'store' => $store
		]);
	}

	public function getCities($departmentId)
	{
		$department = Department::find($departmentId);
		$cities = $department->cities;
		return response()->json($cities);
	}

	public function getSearch(Request $request)
	{
		$departmentId = $request->input('department');
		$cityId = $request->input('city');
		$stores = Store::search([
			'department' => $departmentId,
			'city' => $cityId
		])->get();


		$groups = [];
		foreach($stores as $store) {
			if( !isset($groups[$store->city->id]) ) {
				$item = new \stdClass();
				$item->city = $store->city;
				$item->stores = collect([$store]);
				$groups[$store->city->id] = $item;
			}
			else {
				$groups[$store->city->id]->stores->push($store);
			}
		}
		return response()->json($groups);
	}

}

resources/views/store/pages/certificaciones.blade.php
@extends('store.layouts.default')

@section('title', trans('front.label_certifications'))
@if (isset($metadata['title']['title']))
	@section('title', $metadata['title']['title'])
@endif
@if (isset($metadata['meta']['keyword']))
	@section('keywords', $metadata['meta']['keyword'])
@endif
@if (isset($metadata['meta']['description']))
	@section('description',$metadata['meta']['description'])
@endif
@if (isset($metadata['og']['type']))
	@section('type',$metadata['og']['type'])
@endif
@if (isset($metadata['og']['url']))
	@section('url',$metadata['og']['url'])
@endif
@if (isset($metadata['og']['image']))
	@section('picture',$metadata['og']['image'])
@endif

@section('content')

<section class="container-fluid quienes-somos">
	<div class="col-xs-12 box-big">
		<figure>
			<img class="img-responsive" src="/images/assets/banner_diseno.png" alt="<?= trans('front.label_certifications') ?>">
		</figure>
	</div>
	<div class="clearfix"></div>
	<div class="container">
		<section class="col-xs-12 col-md-8 content-quienes-somos">
			<h1>Certificaciones</h1>
			<article>
				<p>
					Ingresa <a href="http://certificadostributarios.alfagres.com.co/CertificadoWeb/IngresarDatos.jsp">aquí</a> y solicita tu certificado
				</p>
			</article>
			<div class="clearfix"></div>
		</section>
	</div>
</section>


@include('store.partials.front.bannersFooter')


@endsection

resources/views/store/pages/home.blade.php
@extends('store.layouts.default')

@if (isset($metadata['title']['title']))
	@section('title', $metadata['title']['title'])
@endif
@if (isset($metadata['meta']['keyword']))
	@section('keywords', $metadata['meta']['keyword'])
@endif
@if (isset($metadata['meta']['description']))
	@section('description',$metadata['meta']['description'])
@endif
@if (isset($metadata['og']['type']))
	@section('type',$metadata['og']['type'])
@endif
@if (isset($metadata['og']['url']))
	@section('url',$metadata['og']['url'])
@endif
@if (isset($metadata['og']['image']))
	@section('picture',$metadata['og']['image'])
@endif


@section('content')

<!-- Slider -->
<div class="container-fluid sin-padding">
	<div class="">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner">
				<?php if(count($carouselBanners)): ?>
				<?php foreach ($carouselBanners as $key => $banner): ?>
				<div class="item <?= $key == 0 ? 'active' : '' ?>">
					<a href="<?=$banner->detailUrl?>" target="<?= $banner->target ?>">
						<img src="<?= $banner->image_url ?>" alt="">
					</a>
					<div class="btn-go">
						<span class="arrow-down">
							<a href="#ambientes" class="anchorLink"><img src="img/icon/arrow-down.gif" alt=""></a>
						</span>
					</div>
				</div>
				<?php endforeach; ?>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>

<div class="clearfix"></div>

<!-- SECTION AMBIENTES -->
<section class="container" id="ambientes">
	<div class="container section-ambientes-title">
		<h1> <span>{{ trans('front.make') }}</span> {{ trans('front.ambients') }}</h1>
	</div>
	<div class="row layout" id="type-layout">
	</div>
	<!--LAYOUTS-->

	<?php if((int)$currentLayout > (int)0): ?>
	@include('store.partials.home.homeLayout'.$currentLayout)
	<?php endif; ?>

	<?php if( isset($bannersPromoHomeTop[1]) || isset($bannersPromoHomeTop[2]) ): ?>
	<section class="container">
		<hr class="separador hidden-md hidden-lg">
	</section>
	<?php endif; ?>

	<div class="row row-no-margin grid-banners-home">
		<?php if(isset($bannersPromoHomeTop[1])): ?>
		<div class="col-sm-12 col-md-8 col-lg-8 coleccioncoleccion">
			<a href="<?=$bannersPromoHomeTop[1]->detailUrl?>" target="<?= $bannersPromoHomeTop[1]->target?>">
				<img class="img-responsive img-coleccion" src="<?= $bannersPromoHomeTop[1]->image_url ?>" alt="">
			</a>
		</div>
		<?php endif; ?>

		<?php if(isset($bannersPromoHomeTop[2])): ?>
		<div class="hidden-xs hidden-sm col-xs-12 col-sm-4 pinturas-mobile">
			<a href="<?=$bannersPromoHomeTop[2]->detailUrl?>" target="<?=$bannersPromoHomeTop[2]->target?>">
				<img class="img-pinturas hidden-xs" src="<?= $bannersPromoHomeTop[2]->image_url ?>" alt="">
			</a>
			<a href="<?=$bannersPromoHomeTop[2]->detailUrl?>" target="<?=$bannersPromoHomeTop[2]->target?>">
				<img class="img-responsive img-pinturas hidden-sm hidden-md hidden-lg" src="<?= $bannersPromoHomeTop[2]->image_url ?>" alt="Pinturas">
			</a>
		</div>
		<?php endif; ?>
	</div>
</section>
<!-- end SECTION AMBIENTES -->

<!-- SECTION PRODUCTOS -->
<section class="container">
	@include('store.partials.products.productsSearchSlider')
</section>
<!-- end SECTION PRODUCTOS -->

<!-- SECTION IDEAS -->
<section class="container">
	@include('store.partials.front.ideas')
</section>
<!-- end SECTION IDEAS -->

@include('store.partials.front.bannersFooter')

@endsection


@push('scripts')
<script>
	$( document ).ready(function() {
		// activate slider home
		//$('#carousel-example-generic').bcSwipe({ threshold: 50 });

		$("#carousel-example-generic").swiperight(function() {
			$("#carousel-example-generic").carousel('prev');
		});

		$("#carousel-example-generic").swipeleft(function() {
		   $("#carousel-example-generic").carousel('next');
		});

	});
</script>
@endpush

resources/views/store/pages/subhome.blade.php
@extends('store.layouts.default')

@section('title', $category->name)
@section('description', $category->description)
@section('keywords',$category->tags)

@section('content')   

<!-- Slider -->
<div class="container-fluid sin-padding">
	<div class="slider-categoria">
		<img src="<?= $category->header_url ?>" alt="categoria" class="imgcategoria" />
	</div>
</div>
<!-- Fin Slider -->

<div class="clearfix"></div>

<!-- begin SECTION SUB-HOME -->
<section class="container content-subhome" id="ambientes">
	<!-- Ruta -->
	<div class="row sin-padding ruta hidden-xs hidden-sm">
		<ol class="breadcrumb">
			<li><a href="/">{{trans('front.home')}}</a></li>
			<?php foreach ($breadcrumbs as $keyCrumb => $crumb) { ?>
				<?php if ($keyCrumb + 1 == count($breadcrumbs)) { ?>
					<li class="active"><?= $crumb->name ?></li>
				<?php } else { ?>
					<li><a href="<?= $crumb->detailUrl ?>"><?= $crumb->name ?></a></li>
				<?php } ?>

			<?php } ?>
		</ol>
	</div>
	<!-- Fin Rutas -->
	<div class="grid-subhome">
		<div class="row">
			<?php foreach ($items as $key => $lvl3) { ?>
				<div class="col-xs-6 col-sm-<?=$columnas?> col-md-<?=$columnas?> col-lg-<?=$columnas?> categorias-ambientes">
					<?php $child = App\Models\Category::where('parent', $lvl3->id)->get(); ?>
					<a href="<?= $lvl3->detailUrl ?>">
						<img class="img-responsive hidden-xs hidden-sm" src="{{ $lvl3->image_url }}" alt="{{ $lvl3->name }}">
						<img class="img-responsive hidden-md hidden-lg" src="{{ $lvl3->image_mobile_url }}" alt="{{ $lvl3->name }}">
					</a>
					<!--<div class="">{{ $lvl3->name }}</div>-->
				</div>
			<?php } ?>
		</div>
	</div>
	
</section>
<!-- end SECTION SUB-HOME -->
<div class="clearfix"></div>

@include('store.partials.front.newsletter')

<!-- SECTION PRODUCTOS -->
<section class="container" id="productos">
	@include('store.partials.products.productsSearchSlider')
</section>

<!-- end SECTION PRODUCTOS -->

<section class="container">
	@include('store.partials.front.ideas')
</section>

<!-- SECTION BANNERS -->

<?php if(count($bannersPromoSubhomeFooter)>0){ ?>
<section class="container-fluid content-promo">
	<div class="container">
		<section class="container">
			<hr class="separador hidden-md hidden-lg">
		</section>
		<div class="row row-no-margin grid-footer-home">
			<?php if(isset($bannersPromoSubhomeFooter[1])){?>
				<div class="hidden-xs hidden-sm col-md-4 col-lg-4 promo-left sin-padding-left sin-padding-right">
					<a href="<?=$bannersPromoSubhomeFooter[1]->detailUrl?>" target="<?=$bannersPromoSubhomeFooter[1]->target?>">
						<img class="img-responsive" src="<?=$bannersPromoSubhomeFooter[1]->image_url?>" alt="">
					</a>
				</div>
			<?php }?>
			
			<?php if(isset($bannersPromoSubhomeFooter[2])){?>
				<div class="col-md-8 col-lg-8 promo-right sin-padding-right">
					<a href="<?=$bannersPromoSubhomeFooter[2]->detailUrl?>" target="<?=$bannersPromoSubhomeFooter[2]->target?>">
						<img class="img-responsive img-promo-2" src="<?=$bannersPromoSubhomeFooter[2]->image_url?>" alt="">
					</a>
				</div>
			<?php }?>
			
		</div>
	</div>
</section>
<?php }?>

<!-- end SECTION BANNERS -->
@endsection