app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Routes File
  |--------------------------------------------------------------------------
  |
  | Here is where you will register all of the routes in an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::group(['namespace' => 'Store', 'middleware' => ['web', 'locale', 'store']], function() {

	Route::get('/', 'FrontController@home');


	/* Products */

	Route::get('subhome/{id}', 'ProductsController@subhome');


	/* Rutas reales slug */

	Route::get('detail/{id}', 'ProductsController@detail');
	Route::get('color/{id}', 'ProductsController@color');
	Route::get('prods/{id}', 'ProductsController@prods');
	Route::get('moreProds/{id}', 'ProductsController@moreProds');
	Route::get('searchMore/{q}', 'ProductsController@searchMore');

	Route::get('loadCategoryInfo/{id}/{pid?}/{pidc?}', 'ProductsController@loadCategoryInfo');


	Route::get('imageByColor/{id}', 'ProductsController@imageByColor');
	//Route::controller('products', 'ProductsController');
	//Route::controller('stores', 'StoresController');

	/* Users */
	Route::controller('users', 'UsersController');
	Route::post('recoverypassword', 'UsersController@recoveryPassword');
	Route::get('/passwordReset/{id}/{recovery}', 'UsersController@viewPasswordReset');
	Route::post('/passwordReset', 'UsersController@passwordReset');
	Route::post('/newsletter', 'UsersController@postNewsletters');

	/* Blog */
	Route::post('blog/comments/save', 'BlogController@postComment');
	Route::get('blog/{category}/{slug}/{id}', 'BlogController@getArticle');
	Route::controller('blog', 'BlogController');
	
	Route::get('loadMore/{page}', 'FrontController@loadMore');
	Route::get('loadMore/{page}/{category}', 'FrontController@loadMore');
/*pages  store */
//--Route::get('/{url}', 'PageController@getPage'); //---RB ***************************
});

/*
 * AUTH
 */

Route::group(['namespace' => 'Auth', 'middleware' => ['web']], function () {

	Route::get('/login', ['uses' => 'AuthController@getLogin', 'as' => 'auth/login']);

	Route::post('/login', 'AuthController@postLogin');

	Route::get('/register', ['uses' => 'AuthController@getRegister', 'as' => 'auth/register']);

	Route::post('/register', 'AuthController@postRegister');

	Route::get('/logout', ['uses' => 'AuthController@getLogout', 'as' => 'auth/logout']);

	Route::get('/forgot', ['uses' => 'AuthController@getForgot', 'as' => 'auth/forgot']);

	Route::post('/forgot', ['uses' => 'PasswordController@postEmail']);

	Route::get('/password/reset/{token}', ['uses' => 'PasswordController@getReset', 'as' => 'auth/reset']);

	Route::post('/password/reset/{token}', ['uses' => 'PasswordController@postReset']);

	Route::get('/activate/account/{token}', ['uses' => 'AuthController@getActivate', 'as' => 'auth/activate']);

	Route::post('/activate/account/{token}', ['uses' => 'AuthController@postActivate']);

	Route::get('/check/email', ['uses' => 'AuthController@getCheckEmail']);
});

//Route::auth();

/*
 *
 */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['web', 'auth', 'store', 'acl']], function() {

	Route::get('/', function() {
		return redirect(route('admin/dashboard'));
	});

	Route::get('/action/country/{id}', ['uses' => 'AdminController@setCountry']);
	Route::get('/action/lang/{id}', ['uses' => 'AdminController@setLang']);

	Route::get('/dashboard', ['uses' => 'HomeController@dashboard', 'as' => 'admin/dashboard']);

	Route::group(['namespace' => 'Catalog', 'prefix' => 'catalog'], function() {

		/* Categories */
		Route::controller('categories', 'CategoriesController');

		/* Products */

		/*
		  Route::get('products/edit/{id}', 'ProductsController@edit');
		  Route::get('products/show/{id}', 'ProductsController@show');
		  Route::post('products/update/{id}', 'ProductsController@update');
		  Route::get('products/destroy/{id}', 'ProductsController@destroy');
		  Route::post('products/store', 'ProductsController@store');
		  Route::get('products/upload', 'ProductsController@getUpload');
		  Route::get('products/uploadlog', 'ProductsController@getUploadLog');
		  Route::get('products/tags', 'ProductsController@getTags');
		  Route::get('products/productbytags/{tag}', 'ProductsController@productbytags');
		  Route::get('products/borrartags/{tag}', 'ProductsController@borrartags');
		  Route::resource('products', 'ProductsController');
		 */

		Route::get('/check/code/{id?}', ['uses' => 'ProductsController@checkCode']);
		Route::get('products/uploadlog', 'ProductsController@getUploadLog');
		Route::controller('products', 'ProductsController');

		/* Products Images */
		Route::get('productsImages/destroy/{id}', 'ProductsImagesController@destroy');
		Route::controller('productsImages', 'ProductsImagesController');

		/* References */
		Route::get('references', 'ReferencesController@index');
		Route::get('references/edit/{id}', 'ReferencesController@edit');
		Route::get('references/create', 'ReferencesController@create');
		Route::get('references/show/{id}', 'ReferencesController@show');
		Route::post('references/update/{id}', 'ReferencesController@update');
		Route::get('references/destroy/{id}', 'ReferencesController@destroy');
		Route::post('references/store', 'ReferencesController@store');
		Route::get('references/deleteDataSheet/{id}', 'ReferencesController@deleteDataSheet');
		Route::get('references/deleteuManual/{id}', 'ReferencesController@deleteuManual');
		Route::get('references/deletemManual/{id}', 'ReferencesController@deletemManual');
		Route::get('references/deleteGuarantee/{id}', 'ReferencesController@deleteGuarantee');
		Route::get('references/category', 'ReferencesController@category');

		/* Stores */
		Route::controller('stores', 'StoresController');
	});

	Route::group(['namespace' => 'Appearance', 'prefix' => 'appearance'], function() {
		/* Menu */
		Route::get('menu/categories/{id}', 'MenuController@categories');
		//Route::resource('menu', 'MenuController');
		Route::controller('menu', 'MenuController');

		Route::controller('slider', 'SliderController');
		Route::controller('footer', 'FooterController');

		/* Carrusel */
		Route::resource('carrusel', 'CarruselController');
		Route::get('carrusel/edit/{id}', 'CarruselController@edit');
		Route::post('carrusel/update/{id}', 'CarruselController@update');
		Route::get('carrusel/destroy/{id}', 'CarruselController@destroy');
		Route::get('carrusel/change-status/{id}/{status}', 'CarruselController@changeStatus');
		Route::post('carrusel/store', 'CarruselController@store');

		/* Banners home */
		Route::controller('banners_home', 'BannersHomeController');

		/* Banners site */
		Route::controller('banners_site', 'BannersSiteController');
	});

	/* USERS */
	Route::get('profile', 'UsersController@getProfile');
	Route::get('profile/edit', 'UsersController@getEditProfile');
	Route::post('profile/edit', 'UsersController@postEditProfile');
	Route::get('profile/change_password', 'UsersController@getChangePassword');
	Route::post('profile/change_password', 'UsersController@postChangePassword');
	//Route::post('/users/create', 'UsersController@postCreate');
	Route::controller('users', 'UsersController');

	/* CUSTOMERS */
	Route::get('customers', 'CustomersController@index');
	Route::get('customers/show/{id}', 'CustomersController@show');
	Route::get('customers/subscribers', 'CustomersController@subscribers');
	Route::get('customers/unsubscribe/{id}', 'CustomersController@unsubscribe');

	/* COUNTRIES */
	Route::controller('countries', 'CountriesController');

	/* DEPARTMENTS */
	Route::controller('departments', 'DepartmentsController');

	/* CITIES */
	Route::controller('cities', 'CitiesController');

	/* SERVICES */
	Route::controller('services', 'ServicesController');

	/* QUOTES */
	Route::get('quotes', 'QuotesController@index');
	Route::get('quotes/show/{id}', 'QuotesController@show');
	Route::get('quotes/edit/{id}', 'QuotesController@edit');
	Route::get('quotes/setManager', 'QuotesController@setManager');
	Route::get('quotes/setRoom', 'QuotesController@setRoom');
	Route::get('quotes/setStatus', 'QuotesController@setStatus');
	Route::get('quotes/setComment', 'QuotesController@setComment');
	Route::get('quotes/downloadQuotes', 'QuotesController@downloadQuotes');
	Route::controller('quotes', 'QuotesController');
	Route::get('/quotes', ['uses' => 'QuotesController@index', 'as' => 'admin/quotes']);

	/* SETTINGNS */
	Route::controller('settings', 'SettingsController');

	/* BLOGS */
	Route::controller('blog', 'BlogController');

/*pages---*/	
Route::controller('page', 'PageController'); //*

	/*SEO*/
	Route::controller('seo','SeoController');
});

/*
 * 	FRONT
 */
Route::group(['namespace' => 'Store', 'middleware' => ['web']], function() {
	Route::get('/customer/email', ['uses' => 'UsersController@getCheckEmail']);


});


Route::group(['namespace' => 'Store', 'middleware' => ['web', 'locale', 'store']], function() {

Route::get('/{url}', 'PageController@getPage'); //---RB ***************************

});

app/Models/Reference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Reference extends Model
{

	protected $table = 'references';

	const STATUS_DISABLED = 'disabled';
	const STATUS_ACTIVE = 'active';

	protected $fillable = [
		'code',
		'color_code',
		'name',
		'reference_id',
		'image',
		'dimensions',
		'color',
		'tags',
	];

	
	// --------------------- RELATIONS --------------------- //
	
	public function products()
	{
		return $this->hasMany('App\Models\Product', 'reference_id');
	}
	
	public function variations()
	{
		return $this->hasMany('App\Models\Product', 'reference_id');
	}
	
	
	// --------------------- STATIC --------------------- //
	
	public static function getReferenceList()
	{
		return self::where(['status' => self::STATUS_ACTIVE]);
	}

	
	// --------------------- PROPERTIES --------------------- //
	
	public function getImageUrlAttribute()
	{
		$product = $this->products()->first();
		if( !$product ) {
			$product = new Product();
		}
		return $product->imageUrl;
	}
	
	
	public function getDataSheetAttribute($dataSheet){
		if($dataSheet){
			$dataSheet = $dataSheet;
		}

		return $dataSheet;
	}

	public function getMaintenanceManualAttribute($maintenanceManual){
		if($maintenanceManual){
			$maintenanceManual = $maintenanceManual;
		}
		
		return $maintenanceManual;
	}

	public function getGuaranteeAttribute($guarantee){
		if($guarantee){
			$guarantee = $guarantee;
		}
	
		return $guarantee;
	}

	public function getUserManualAttribute($userManual){
		if($userManual){
			$userManual = $userManual;
		}
		
		return $userManual;
	}
	
	
	public function getQualitySeal()
	{
		$qualitySeals = [];
		$seals = explode(',', $this->quality_seal);

		foreach( $seals as $seal ) {
			$aux['text'] = $seal;
			$pdf = "";

			switch( $seal ) {
				case 01:
					$pdf = "/files/products/quality-seals/Sello de calidad 01.pdf";
					break;
				case 02:
					$pdf = "/files/products/quality-seals/Sello de calidad 02.pdf";
					break;
				case 03:
					$pdf = "/files/products/quality-seals/Sello de calidad 03.pdf";
					break;
				case 04:
					$pdf = "/files/products/quality-seals/Sello de calidad 04.pdf";
					break;
				case 05:
					$pdf = "/files/products/quality-seals/Sello de calidad 05.pdf";
					break;
				case 06:
					$pdf = "/files/products/quality-seals/Sello de calidad 06.pdf";
					break;
			}

			$aux['link'] = $pdf;
			$qualitySeals[] = $aux;
		}

		return $qualitySeals;
	}

}

resources/views/store/partials/info/datasheets.blade.php
@section('content')  

<!-- Content -->
<section class="container-fluid info-cliente-producto">
	<div class="container">
		<!-- Ruta -->
		<div class="row row-no-margin sin-padding ruta hidden-xs hidden-sm">
			<div class="col-xs-12">
				<ol class="breadcrumb sin-padding">
					<li><a href="/">{{ trans('front.home') }}</a></li>
					<li><a href="<?= url(trans('routes.client_info')) ?>">{{ trans('front.customer_information') }}</a></li>
					<li class="active">{{ trans('front.datasheets') }}</li>
				</ol>
			</div>
		</div>
		<!-- Fin Rutas -->

		<div class="row row-no-margin">
			<div class="col-xs-12">
				<h1>{{ trans('front.datasheets') }}</h1>
			</div>	
		</div>

		<!-- Filtros -->
		<div class="row row-no-margin sin-padding hidden-xs hidden-sm">
			<div class="col-sm-6 col-sm-offset-3 filtros">
				<div class="col-xs-6">
					<select class="cs-select cs-skin-underline select-info" id="category">
						<option value="" disabled selected>Categoria</option>
						@foreach ($grouped as $group)
						<option value="{{ $group[0]->cid }}">{{ $group[0]->cname }}</option>
						@endforeach
					</select>
				</div>
				<div class="col-xs-6" id="product-col">
					<select class="cs-select cs-skin-underline select-info" id="product">
						<option value="" disabled selected>Productos</option>
					</select>
				</div>
			</div>
		</div>
		<!-- Fin Filtros -->
		<div id="results">
			@foreach ($grouped as $group)
				<div class="row row-no-margin container-results">
				<h2 class="tit-purple">{{ $group[0]->cname }}</h2>
					@foreach ($group as $i => $product)
						<div class="col-xs-6 col-sm-3">
							<a href="{{ $product->data_sheet }}" download>
								<figure>
									<img src="/images/icon-item-info.png" alt="">
								</figure>
								<p class="tit-item-info">{{ $product->name }}</p>
							</a>
						</div>
						@if($i == 7)
							<div class="col-xs-12 ver-mas-purple">
								<a href="#" class="more" data-id="{{ $product->cid }}">{{ trans('front.see_more') }}</a>
							</div>
							@break
						@endif
					@endforeach
					<div id="mini-loader" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center" style="display: none; margin-top: 10px;">
						<div class="internal-loading">
							<div class="internal-loader"></div>
						</div>
						<!--<img src="/images/loader.gif" style="width: 30px; height: 30px;"/>-->
					</div>
				</div>
			@endforeach
		</div>
		
	</div>
</section>
<!-- Fin Content -->
@endsection

@push('scripts')
<script>

var product = document.querySelector('#product');
productFx = new SelectFx( product, {} );

var selectElement2 = document.querySelector('#category');
new SelectFx( selectElement2, {
	onChange: function(val) {
		showLoader();//Mostrar loader
		var select = $('#category');

		var output = [];
		$('#results').html('');
		$.getJSON("/clientInfoByCatId/"+ select.val() +"/datasheets/", function(jsonData){
			var toAppend = '';
			$.each(jsonData, function(i,data)
			{
				toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.data_sheet+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
			});
			$('#results').html(toAppend);
			hideLoader();
			// remove and recreate product dropdown
			var productEl = $('#product').empty().clone();
			$(productFx.selEl).remove();

			output.push('<option disabled selected>Producto</option>');
			$.each(jsonData, function(i,data)
			{
				output.push('<option value="' + data.id + '">'+ data.name +'</option>');
			});

			$('#product-col').append(productEl);
			$('#product').html(output.join(''));

			product = document.querySelector('#product');
			productFx = new SelectFx( product, {
				onChange: function(val){
					showLoader();//Mostrar loader
					$('#results').html('');
					$.getJSON("/clientInfoProd/"+ val +"/", function(jsonData){
						var toAppend = '';
						$.each(jsonData, function(i,data){
							toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.data_sheet+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
						});
						$('#results').html(toAppend);
						hideLoader();//Ocultar loader
					});
				}
			});
		});
	}
});

$('.container-results').on('click', '.more', function (e) {
	var output = [];
	var catid = $(this).attr("data-id");
	var me = $(this);
	me.hide();
	me.parents(".container-results").children('#mini-loader').css('display', 'block');
	$.getJSON("/loadMore/"+catid+"/datasheets/", function(jsonData){
		console.log(jsonData);
		var toAppend = '';
		$.each(jsonData, function(i,data)
		{
			toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.data_sheet+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
		});
		me.parents(".container-results").append(toAppend);
		me.parents(".container-results").children('#mini-loader').css('display', 'none');
	});
	e.preventDefault();
});

</script>
@endpush

resources/views/store/partials/info/manuals.blade.php
@section('content')  

<!-- Content -->
<section class="container-fluid info-cliente-producto">
	<div class="container">
		<!-- Ruta -->
		<div class="row row-no-margin sin-padding ruta hidden-xs hidden-sm">
			<div class="col-xs-12">
				<ol class="breadcrumb sin-padding">
					<li><a href="/">{{ trans('front.home') }}</a></li>
					<li><a href="<?= url(trans('routes.client_info')) ?>">{{ trans('front.customer_information') }}</a></li>
					<li class="active">{{ trans('front.manuals') }}</li>
				</ol>
			</div>
		</div>
		<!-- Fin Rutas -->
		
		<div class="row row-no-margin">
			<div class="col-xs-12">
				<h1>{{ trans('front.manuals') }}</h1>
			</div>	
		</div>

		<!-- Filtros -->
		<div class="row row-no-margin  sin-padding hidden-xs hidden-sm">
			<div class="col-sm-6 col-sm-offset-3 filtros">
				<div class="col-xs-6">
					<select class="cs-select cs-skin-underline select-info" id="category">
						<option value="" disabled selected>Categoria</option>
						@foreach ($grouped as $group)
						<option value="{{ $group[0]->cid }}">{{ $group[0]->cname }}</option>
						@endforeach
					</select>
				</div>
				<div class="col-xs-6" id="product-col">
					<select class="cs-select cs-skin-underline select-info" id="product">
						<option value="" disabled selected>Productos</option>
					</select>
				</div>
			</div>
		</div>
		<!-- Fin Filtros -->
		<div id="results">
			@foreach ($grouped as $group)
				<div class="row row-no-margin container-results">
				<h2 class="tit-purple">{{ $group[0]->cname }}</h2>
					@foreach ($group as $i => $product)
						<div class="col-xs-6 col-sm-3">
							<a href="{{ $product->user_manual }}" download>
								<figure>
									<img src="/images/icon-item-info.png" alt="">
								</figure>
								<p class="tit-item-info">{{ $product->name }}</p>
							</a>
						</div>
						@if($i == 7)
							<div class="col-xs-12 ver-mas-purple">
								<a href="#" class="more" data-id="{{ $product->cid }}">{{ trans('front.see_more') }}</a>
							</div>
							@break
						@endif
					@endforeach
					<div id="mini-loader" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center" style="display: none; margin-top: 10px;">
						<div class="internal-loading">
							<div class="internal-loader"></div>
						</div>
						<!--<img src="/images/loader.gif" style="width: 30px; height: 30px;"/>-->
					</div>
				</div>
			@endforeach
		</div>
		
	</div>
</section>
<!-- Fin Content -->
@endsection

@push('scripts')
<script>

var product = document.querySelector('#product');
productFx = new SelectFx( product, {} );

var selectElement2 = document.querySelector('#category');
new SelectFx( selectElement2, {
	onChange: function(val) {
		showLoader();//Mostrar loader
		var select = $('#category');

		var output = [];
		$('#results').html('');
		$.getJSON("/clientInfoByCatId/"+ select.val() +"/manuals/", function(jsonData){
			var toAppend = '';
			$.each(jsonData, function(i,data){
				toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.user_manual+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
			});
			$('#results').html(toAppend);
			hideLoader();//Ocultar loader
			// remove and recreate product dropdown
			var productEl = $('#product').empty().clone();
			$(productFx.selEl).remove();

			output.push('<option disabled selected>Producto</option>');
			$.each(jsonData, function(i,data)
			{
				output.push('<option value="' + data.id + '">'+ data.name +'</option>');
			});

			$('#product-col').append(productEl);
			$('#product').html(output.join(''));

			product = document.querySelector('#product');
			productFx = new SelectFx( product, {
				onChange: function(val){
					showLoader();//Mostrar loader
					$('#results').html('');
					$.getJSON("/clientInfoProd/"+ val +"/", function(jsonData){
						var toAppend = '';
						$.each(jsonData, function(i,data){
							toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.user_manual+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
						});
						$('#results').html(toAppend);
						hideLoader();//Ocultar loader
					});
				}
			});
		});
	}
});

$('.container-results').on('click', '.more', function (e) {
	var output = [];
	var catid = $(this).attr("data-id");
	var me = $(this);
	me.hide();
	me.parents(".container-results").children('#mini-loader').css('display', 'block');
	$.getJSON("/loadMore/"+catid+"/manuals/", function(jsonData){
		var toAppend = '';
		$.each(jsonData, function(i,data){
			toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.maintenance_manual+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
		});
		me.parents(".container-results").append(toAppend);
		me.parents(".container-results").children('#mini-loader').css('display', 'none');
	});
	e.preventDefault();
});

</script>
@endpush

resources/views/store/partials/info/warranties.blade.php
@section('content')
<!-- Content -->
<section class="container-fluid info-cliente-producto">
	<div class="container">
		
		<!-- Ruta -->
		<div class="row row-no-margin sin-padding ruta hidden-xs hidden-sm">
			<div class="col-xs-12">
				<ol class="breadcrumb sin-padding">
					<li><a href="/">{{ trans('front.home') }}</a></li>
					<li><a href="<?= url(trans('routes.client_info')) ?>">{{ trans('front.customer_information') }}</a></li>
					<li class="active">{{ trans('front.warranties') }}</li>
				</ol>
			</div>
		</div>
		<!-- Fin Rutas -->
		
		<div class="row row-no-margin">
			<div class="col-xs-12">
				<h1>{{ trans('front.warranties') }}</h1>
			</div>	
		</div>

		<!-- Filtros -->
		<div class="row row-no-margin sin-padding hidden-xs hidden-sm">
			<div class="col-sm-6 col-sm-offset-3 filtros">
				<div class="col-xs-6">
					<select class="cs-select cs-skin-underline select-info" id="category">
						<option value="" disabled selected>Categoria</option>
						@foreach ($grouped as $group)
						<option value="{{ $group[0]->cid }}">{{ $group[0]->cname }}</option>
						@endforeach
					</select>
				</div>
				<div class="col-xs-6" id="product-col">
					<select class="cs-select cs-skin-underline select-info" id="product">
						<option value="" disabled selected>Productos</option>
					</select>
				</div>
			</div>
		</div>
		<!-- Fin Filtros -->
		<div id="results">
			@foreach ($grouped as $group)
				<div class="row row-no-margin container-results">
				<h2 class="tit-purple">{{ $group[0]->cname }}</h2>
					@foreach ($group as $i => $product)
							<div class="col-xs-6 col-sm-3">
								<a href="{{ $product->guarantee }}" download>
									<figure>
										<img src="/images/icon-item-info.png" alt="">
									</figure>
									<p class="tit-item-info">{{ $product->name }}</p>
								</a>
							</div>
							@if($i == 7)
								<div class="col-xs-12 ver-mas-purple">
									<a href="#" class="more" data-id="{{ $product->cid }}">{{ trans('front.see_more') }}</a>
								</div>
								@break
							@endif
					@endforeach
					<div id="mini-loader" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center" style="display: none; margin-top: 10px;">
						<div class="internal-loading">
							<div class="internal-loader"></div>
						</div>
						<!--<img src="/images/loader.gif" style="width: 30px; height: 30px;"/>-->
					</div>
				</div>
			@endforeach
		</div>
	</div>
</section>
<!-- Fin Content -->
@endsection

@push('scripts')
<script>

var product = document.querySelector('#product');
productFx = new SelectFx( product, {} );

var selectElement2 = document.querySelector('#category');
new SelectFx( selectElement2, {
	onChange: function(val) {
		showLoader();//Mostrar loader
		var select = $('#category');

		var output = [];
		$('#results').html('');
		$.getJSON("/clientInfoByCatId/"+ select.val() +"/warranties/", function(jsonData){
			var toAppend = '';
			$.each(jsonData, function(i,data){
				toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.guarantee+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
			});
			$('#results').html(toAppend);
			hideLoader();//Ocultar loader

			// remove and recreate product dropdown
			var productEl = $('#product').empty().clone();
			$(productFx.selEl).remove();

			output.push('<option disabled selected>Producto</option>');
			$.each(jsonData, function(i,data){
				output.push('<option value="' + data.id + '">'+ data.name +'</option>');
			});

			$('#product-col').append(productEl);
			$('#product').html(output.join(''));

			product = document.querySelector('#product');
			productFx = new SelectFx( product, {
				onChange: function(val){
					showLoader();//Mostrar loader
					$('#results').html('');
					$.getJSON("/clientInfoProd/"+ val +"/", function(jsonData){
						var toAppend = '';
						$.each(jsonData, function(i,data){
							toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.guarantee+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
						});
						$('#results').html(toAppend);
						hideLoader();//Ocultar loader
					});
				}
			});
		});
	}
});


$('.container-results').on('click', '.more', function (e) {
	var output = [];
	var catid = $(this).attr("data-id");
	var me = $(this);
	me.hide();
	me.parents(".container-results").children('#mini-loader').css('display', 'block');
	$.getJSON("/loadMore/"+catid+"/warranties/", function(jsonData){
		console.log(jsonData);
		var toAppend = '';
		$.each(jsonData, function(i,data)
		{
			toAppend += '<div class="col-xs-6 col-sm-3"><a href="'+data.guarantee+'" download><figure><img src="/images/icon-item-info.png" alt=""></figure><p class="tit-item-info">'+data.name+'</p></a></div>';
		});
		me.parents(".container-results").append(toAppend);
		me.parents(".container-results").children('#mini-loader').css('display', 'none');
	});
	e.preventDefault();
});

</script>
@endpush